### PR TITLE
check for OpenCV 3.(2+)

### PR DESCRIPTION
**Pull request by JStech**
When building with OpenCV 3.4, the target markers fail with this error:

    moveit_calibration/moveit_calibration_plugins/handeye_calibration_target/src/handeye_target_charuco.cpp:196:17: 
        error: ‘struct cv::aruco::DetectorParameters’ has no member named ‘cornerRefinementMethod’; did you mean 
        ‘cornerRefinementWinSize’?
     params_ptr->cornerRefinementMethod = cv::aruco::CORNER_REFINE_NONE;

This is because the correct code for OpenCV 3.4 is guarded by preprocessor checks that specifically look for 3.2. This PR just switches that check to pass for any minor version >=2. (Related to #5 .)

### CODE REVIEW

**Comment by JStech** [comment]
Well, now I'm all confused. It does look like 3.2.0 uses the `doCornerRefinement` parameter, but 3.4.5 uses `cornerRefinementMethod`, but this change does seem to fix a build on 3.4 for us. I'm going to close this PR for now.
